<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Update="System.Drawing">
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BarcodeStandard\BarcodeStandard.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Barcode.ico" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>